# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-prod
#   namespace: django
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     email: pumej1985@gmail.com
#     privateKeySecretRef:
#       name: letsencrypt-prod
#     solvers:
#       - http01:
#           ingress:
#             class: nginx

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: django
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: pumej1985@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - http01:
          ingress:
            class: nginx